// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTLV_hYfqGfYasL-cTceDMzDtApGAQw7g',
    appId: '1:549127138761:web:f1c37730d10a9f147f4c18',
    messagingSenderId: '549127138761',
    projectId: 'quizflow-788a0',
    authDomain: 'quizflow-788a0.firebaseapp.com',
    storageBucket: 'quizflow-788a0.appspot.com',
    measurementId: 'G-HX66JJ83Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvm5Xd3O_FGXv-Yq6IUaA52SUEzXBnFIY',
    appId: '1:549127138761:android:668c736eec4c65f97f4c18',
    messagingSenderId: '549127138761',
    projectId: 'quizflow-788a0',
    storageBucket: 'quizflow-788a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6tEIMKrAEqoZFIbss70hPt6XVbbftphs',
    appId: '1:549127138761:ios:18011397546575947f4c18',
    messagingSenderId: '549127138761',
    projectId: 'quizflow-788a0',
    storageBucket: 'quizflow-788a0.appspot.com',
    iosClientId: '549127138761-jsg6qv1poelip0rh2bunbt51r80tlput.apps.googleusercontent.com',
    iosBundleId: 'com.ignacio.quizFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6tEIMKrAEqoZFIbss70hPt6XVbbftphs',
    appId: '1:549127138761:ios:18011397546575947f4c18',
    messagingSenderId: '549127138761',
    projectId: 'quizflow-788a0',
    storageBucket: 'quizflow-788a0.appspot.com',
    iosClientId: '549127138761-jsg6qv1poelip0rh2bunbt51r80tlput.apps.googleusercontent.com',
    iosBundleId: 'com.ignacio.quizFlow',
  );
}
